FROM node:22

WORKDIR /app

COPY ../../package*.json ./

COPY ../../nx.json ./
COPY ../../tsconfig.base.json ./

COPY ../../.env ./

COPY ../../libs ./libs

RUN npm ci

COPY apps/user ./apps/user

EXPOSE 4000

RUN npx nx reset


CMD ["npx", "nx", "serve", "user", "--host", "0.0.0.0"]
