FROM node:22
WORKDIR /app
COPY ../../package.json ../../package-lock.json ./
RUN npm install --only=production
COPY . .
RUN npm run build --workspace=user
EXPOSE 4000
CMD ["node", "dist/apps/user/main.js"]
