apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-app
  template:
    metadata:
      labels:
        app: order-app
    spec:
      containers:
        - name: order-app
          image: stepheng323/order-service
          env:
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq-cluster-ip:5672

            - name:  EXCHANGE_NAME
              value: e_commerce

            - name:  PORT
              value: '4002'

            - name:  QUEUE_NAME
              value: order_queue

            - name: DATABASE_URL
              value: postgresql://postgres:$(USER_DB_PASSWORD)@order-db-cluster-ip:5432/postgres

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: general-secret
                  key: JWT_SECRET
          ports:
            - containerPort: 4002

---
apiVersion: v1
kind: Service
metadata:
  name: order-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: order-app
  ports:
    - port: 4002
      targetPort: 4002





