apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-app
  template:
    metadata:
      labels:
        app: product-app
    spec:
      containers:
        - name: product-app
          image: nestjs-scaffold-product
          env:
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq-cluster-ip:5672

            - name:  EXCHANGE_NAME
              value: e_commerce

            - name:  PORT
              value: '4001'

            - name:  QUEUE_NAME
              value: product_queue

            - name: DATABASE_URL
              value: mysql://$(DB_USER):$(DB_PASSWORD)@product-cluster-ip:3306/$(DB_NAME)

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: "general-secret"
                  key: JWT_SECRET

            - name: DB_HOST
              value: product-cluster-ip

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: "product-app-secret"
                  key: PRODUCT_DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: "product-app-secret"
                  key: PRODUCT_DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "product-app-secret"
                  key: PRODUCT_DB_PASSWORD
          imagePullPolicy: Never
          ports:
            - containerPort: 4001

---
apiVersion: v1
kind: Service
metadata:
  name: product-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: product-app
  ports:
    - port: 4001
      targetPort: 4001





