apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: user-app
          image: stepheng323/user-service:latest
          env:
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq-cluster-ip:5672

            - name: EXCHANGE_NAME
              value: e_commerce

            - name: PORT
              value: '4000'

            - name: QUEUE_NAME
              value: user_queue

            - name: USER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-app-secret
                  key: USER_DB_PASSWORD

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: user-app-secret
                  key: DATABASE_URL

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: general-secret
                  key: JWT_SECRET
          ports:
            - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: user-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: user-app
  ports:
    - port: 4000
      targetPort: 4000
